# File: .github/workflows/repo-sync.yml
name: sync-happy888888/BiliExp
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ dockerjs ]
  repository_dispatch:
    types: sync-happy888888/BiliExp
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-happy888888/BiliExp
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/happy888888/BiliExp"
          sync_tags: "1.1.9"
          destination_branch: "BiliExp"
          github_token: ${{ secrets.PAT }}
